version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          app-name: "worf-is"
          branch: master 
          api-key: HEROKU_API_KEY # this environment variable goes in CircleCI
        
